[build]
builder = "RAILPACK"
buildCommand = "npm install && npm run build"
watchPatterns = ["/bot/**"]

[deploy]
startCommand = "npm run start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
